### ISSUE TITLE
CLIP reload type bug - clip size reduced to 0

### ISSUE THREAD

**Issue by uksspy** [dmulloy2/SwornGuns#31]
Video of the bug: http://youtu.be/PEi1GliqQmU 
Explanation: When they reload type CLIP is used, guns have a clip size of 0 and cannot fire.
Edit: Using build #353

**Comment by dmulloy2** [comment]
You have to set the size of the clip in the gun config, ````clipSize=[clip size]````

**Comment by uksspy** [comment]
Ok, thanks. I did notice that when firing the total ammo count increases by 1 until the clip is empty, at which point the ammo count resets to the correct number.
