### ISSUE TITLE
getAmmoAmtNeeded() never defined?

### ISSUE THREAD

**Issue by phantamanta44** [dmulloy2/SwornGuns#32]
Gun.getAmmoAmtNeeded() seems to be referenced [here](https://github.com/dmulloy2/SwornGuns/blob/master/src/main/java/net/dmulloy2/swornguns/types/GunPlayer.java#L243), but it doesn't ever seem to be defined in the Gun class (or anywhere else either, for that matter).

**Comment by dmulloy2** [comment]
The method defined [here](https://github.com/dmulloy2/SwornGuns/blob/master/src/main/java/net/dmulloy2/swornguns/types/Gun.java#L68), then it is converted into a getter and a setter using [lombok](https://projectlombok.org/).

**Comment by phantamanta44** [comment]
Ah, I see. I didn't notice the `@Data` annotation.
