### ISSUE TITLE
no gunshot sounds?

### ISSUE THREAD

**Issue by chillerkraft** [dmulloy2/SwornGuns#35]
i just started using this plugin, and i noticed that the guns don't make any sounds when fired

18.06 23:57:02 [Server] INFO You are 5 version(s) behind
18.06 23:57:00 [Server] INFO Checking version, please wait...
18.06 23:57:00 [Server] INFO This server is running CraftBukkit version git-Spigot-44c59bf-b023c53 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

using SwornGuns #362

crap... i'm in offline mode, and the server host is using java 7... i just noticed that i won't get any support now, and that's probably the problem...

**Comment by chillerkraft** [comment]
okay i'm now in online mode with the server running on java 8 (a different host, this one uses java 8)

19.06 02:12:30 [Server] INFO You are 14 version(s) behind
19.06 02:12:28 [Server] INFO Checking version, please wait...
19.06 02:12:28 [Server] INFO This server is running CraftBukkit version git-Spigot-b3c0272-7723b90 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

still the exact same situation, the gun shots aren't making any sound
the sound the bullet would make as it explodes out of the gun.
it seems like this should be happening when i look at the config,
and because i'd assume the plugin would have that... please help (:

**Comment by phantamanta44** [comment]
Could you please provide your gun config file?

**Comment by chillerkraft** [comment]
http://pastebin.com/0Ac2jx3E

**Comment by chillerkraft** [comment]
http://pastebin.com/0Ac2jx3E
