### ISSUE TITLE
Gun test

### ISSUE THREAD

**Issue by MineswornNewone** [dmulloy2/SwornGuns#36]
I was recently asked to do some testing on the guns and here is what I found. 
Shotgun- no matter how many pellets hit the target or how close you are the damage turns out to be between 1 and 1/2 hearts of damage 
Pistol- In my testing the farther away you stand from the target with the pistol the more damage you do to the target. An up close chest shot only did 1 heart, but a shot from about 25-30 blocks away did 6 hearts of damage 
These two guns are the only two that i have found problems with but i will continue going into more detailed testing of all the other guns in a future time.

**Comment by dmulloy2** [comment]
This should be fixed in the latest build. Try it and let me know if this is still an issue.
