### ISSUE TITLE
lethal bug, recent build

### ISSUE THREAD

**Issue by GarretSidzaka** [dmulloy2/SwornGuns#37]
8-30-2015 11:57:20 [INFO] Porcupine_Rulez issued server command: /f money
08-30-2015 11:57:23 [INFO] Huggy52 lost connection: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host
08-30-2015 11:57:23 [INFO] Huggy52 left the game.
08-30-2015 11:57:23 [WARN] [SwornGuns] Encountered an exception while ticking player null: java.lang.NullPointerException
Affected classes:
	net.dmulloy2.swornguns.types.GunPlayer.tick(Line 138) [SwornGuns.jar]
	net.dmulloy2.swornguns.SwornGuns$UpdateTimer.run(Line 433) [SwornGuns.jar]
	org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(Line 71) [spigot-1.8.8.jar]
	org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(Line 350) [spigot-1.8.8.jar]
	java.lang.Thread.run(Native Method)
08-30-2015 11:57:24 [WARN] [SwornGuns] Encountered an exception while ticking player null: java.lang.NullPointerException
Affected classes:
	net.dmulloy2.swornguns.types.GunPlayer.tick(Line 138) [SwornGuns.jar]
	net.dmulloy2.swornguns.SwornGuns$UpdateTimer.run(Line 433) [SwornGuns.jar]
	org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(Line 71) [spigot-1.8.8.jar]
	org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(Line 350) [spigot-1.8.8.jar]
	java.lang.Thread.run(Native Method)
08-30-2015 11:57:24 [WARN] [SwornGuns] Encountered an exception while ticking player null: 

that repeated a bit

then followed by hours of
08-30-2015 12:48:24 [WARN] [SwornGuns] Encountered an exception while ticking player null: java.lang.NullPointerException
Affected classes:
08-30-2015 12:48:25 [WARN] [SwornGuns] Encountered an exception while ticking player null: java.lang.NullPointerException
Affected classes:
08-30-2015 12:48:25 [WARN] [SwornGuns] Encountered an exception while ticking player null: java.lang.NullPointerException
Affected classes:
08

**Comment by dmulloy2** [comment]
Pretty sure this was fixed in build 392, try that one.

**Comment by GarretSidzaka** [comment]
thanks i updated and will see if it happens again :)
