### ISSUE TITLE
stack trace

### ISSUE THREAD

**Issue by GarretSidzaka** [dmulloy2/SwornGuns#38]
01-19-2016 07:39:41 [INFO] michael_rahon left the game.
01-19-2016 07:39:41 [WARN] [SwornGuns] Encountered an exception while ticking bullet Bullet[shooter=null, shotFrom=sniper, id=163881]: java.lang.IllegalArgumentException: identifier cannot be null!
Affected classes:
	org.apache.commons.lang.Validate.notNull(Line 192) [spigot-1.8.8.jar]
	net.dmulloy2.swornguns.util.Util.matchPlayer(Line 62) [SwornGuns.jar]
	net.dmulloy2.swornguns.types.GunPlayer.getPlayer(Line 222) [SwornGuns.jar]
	net.dmulloy2.swornguns.types.Bullet.tick(Line 188) [SwornGuns.jar]
	net.dmulloy2.swornguns.SwornGuns$UpdateTimer.run(Line 489) [SwornGuns.jar]
	org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(Line 71) [spigot-1.8.8.jar]
	org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(Line 350) [spigot-1.8.8.jar]
	java.lang.Thread.run(Native Method)
01-19-2016 07

**Comment by dmulloy2** [comment]
Looks like someone shot a gun then left the server. Should be a pretty simple fix when I get the chance.
