### ISSUE TITLE
Velocity [WARN]

### ISSUE THREAD

**Issue by FunnyCraft** [dmulloy2/SwornGuns#39]
http://pastebin.com/JY4P0e6v

**Comment by phantamanta44** [comment]
Can we see your gun file?

**Comment by FunnyCraft** [comment]
http://rghost.ru/private/89R9XrGMB/9df96c0e42b148fea8da633a69bc89f4

**Comment by FunnyCraft** [comment]
Скачать - [download].

**Comment by phantamanta44** [comment]
Looks like CB added a check for high velocity for whatever reason:
https://hub.spigotmc.org/stash/projects/PAPER/repos/paperspigot/browse/Spigot-Server-Patches/0098-Add-velocity-warnings.patch

**Comment by FunnyCraft** [comment]
how to fix something, you can?

**Comment by phantamanta44** [comment]
In `paper.yml`, you'll want to set the key `warnWhenSettingExcessiveVelocity` to `false`.

**Comment by FunnyCraft** [comment]
23.04 17:10:53 [Server] INFO java.nio.channels.ClosedChannelException
23.04 17:10:53 [Server] WARN An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
what this?

**Comment by phantamanta44** [comment]
Looks like an issue with Minecraft's netty implementation? I doubt it's something related to SwornGuns.

**Comment by dmulloy2** [comment]
That addition by paper makes a ton of sense...

The exception caught message isn't related to SwornGuns.
