### ISSUE TITLE
Fired projectile hits self

### ISSUE THREAD

**Issue by RoboMWM** [dmulloy2/SwornGuns#40]
I'm still thinking about whether I'll fully switch over from Crackshot to this (since it seems default weapons use the literal tool instead of looking at lore), but during my tests, I noticed that if a block/wall was behind me when I fire the pistol, the projectile (snowball) hit me. I remember reading somewhere about projectiles borked in 1.9, so that probably has a bit to do with it.

Using paper 1.9.2, SwornGuns build 415

**Comment by dmulloy2** [comment]
This might be something to do with paper, although I haven't actually tested it yet.
https://github.com/dmulloy2/SwornGuns/issues/39

**Comment by RoboMWM** [comment]
afaik this is actually a Minecraft issue https://bugs.mojang.com/browse/MC-88491

Not sure if there's any way to workaround it. For now I'm using https://www.spigotmc.org/resources/projectilebugfix.22314/
